server:
  port: 9091

spring:  application:    name: config-service  cloud:    config:      server:
        git:
          uri: https://github.com/opdevale/ecommerse-microservices/common-config-file
          #clone-on-start: true      
      